
ALTER TABLE `vehicles`
ADD COLUMN IF NOT EXISTS `nos` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_spoiler` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_hood` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_roof` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_sideskirt_l` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_sideskirt_r` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_lamps` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_nitro` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_exhaust` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_wheels` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_stereo` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_hydraulics` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_front_bumper` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_rear_bumper` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_vent_right` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mod_vent_left` INT NOT NULL DEFAULT 0;
