
ALTER TABLE `vehicles`
ADD COLUMN `nos` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_spoiler` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_hood` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_roof` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_sideskirt_l` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_sideskirt_r` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_lamps` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_nitro` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_exhaust` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_wheels` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_stereo` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_hydraulics` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_front_bumper` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_rear_bumper` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_vent_right` INT NOT NULL DEFAULT 0,
ADD COLUMN `mod_vent_left` INT NOT NULL DEFAULT 0;
