-- ERP v1.28 Clean Audio Zones + Radio Stations Migration
-- Old `audio_streams` is replaced by `audiozones`.

ALTER TABLE `accounts`
ADD COLUMN IF NOT EXISTS `fav_radio` INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS `radiostations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `category` VARCHAR(32) NOT NULL DEFAULT 'General',
  `enabled` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `audiozones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL DEFAULT 'Audio Zone',
  `url` VARCHAR(255) NOT NULL,
  `x` FLOAT NOT NULL DEFAULT 0,
  `y` FLOAT NOT NULL DEFAULT 0,
  `z` FLOAT NOT NULL DEFAULT 0,
  `range` FLOAT NOT NULL DEFAULT 30,
  `vw` INT NOT NULL DEFAULT 0,
  `interior` INT NOT NULL DEFAULT 0,
  `enabled` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Optional cleanup. Uncomment only if you want to delete the old unused table from your database:
-- DROP TABLE IF EXISTS `audio_streams`;

INSERT IGNORE INTO `radiostations` (`id`, `name`, `url`, `category`, `enabled`) VALUES
(1, 'Sha3by FM', 'http://radio95.radioca.st/', 'Egyptian', 1),
(2, 'Zeno Fm - Sha3by', 'http://stream-176.zeno.fm/cwbmdw0rh98uv', 'Egyptian', 1),
(3, 'Alukah Quran Radio', 'http://radio.alukah.net/quran.mp3', 'Quran', 1),
(4, 'Quran Radio Qassimy', 'http://radio.qassimy.com:8000/stream', 'Quran', 1),
(5, 'Quran Radio Jordan', 'http://jrtv-live.ercdn.net/jrradio/quranradio.m3u8', 'Quran', 1),
(6, 'BBC Arabic', 'http://stream.live.vc.bbcmedia.co.uk/bbc_arabic_radio', 'Arabic', 1),
(7, 'Monte Carlo Doualiya', 'http://montecarlodoualiya128k.ice.infomaniak.ch/mc-doualiya.mp3', 'Arabic', 1),
(8, 'Radio Orient', 'http://stream.radioorient.com/radioorient', 'Arabic', 1),
(9, 'Medi 1 Arabic', 'http://live.medi1.com/RadioMedi1', 'Arabic', 1),
(10, 'Al Jazeera Arabic Audio', 'http://live-hls-audio-web-aja.getaj.net/VOICE-AJA/index.m3u8', 'Arabic', 1),
(11, 'BBC World Service', 'http://stream.live.vc.bbcmedia.co.uk/bbc_world_service', 'News', 1),
(12, 'Dutch Radio 1 Test', 'http://icecast.omroep.nl/radio1-bb-mp3', 'Test', 1),
(13, 'France Info', 'http://icecast.radiofrance.fr/franceinfo-midfi.mp3', 'News', 1),
(14, 'FIP Radio', 'http://icecast.radiofrance.fr/fip-midfi.mp3', 'World', 1),
(15, 'France Inter', 'http://icecast.radiofrance.fr/franceinter-midfi.mp3', 'Talk', 1),
(16, 'Radio Paradise Main 192', 'http://stream.radioparadise.com/mp3-192', 'Chill', 1),
(17, 'Radio Paradise Mellow 192', 'http://stream.radioparadise.com/mellow-192', 'Chill', 1),
(18, 'Radio Paradise Rock 192', 'http://stream.radioparadise.com/rock-192', 'Rock', 1),
(19, 'Radio Paradise Global 192', 'http://stream.radioparadise.com/global-192', 'World', 1),
(20, 'Nightride FM', 'http://stream.nightride.fm/nightride.mp3', 'Synthwave', 1),
(21, 'Nightride Chill', 'http://stream.nightride.fm/chillsynth.mp3', 'Synthwave', 1),
(22, 'Nightride Darksynth', 'http://stream.nightride.fm/darksynth.mp3', 'Synthwave', 1),
(23, 'Nightride EBSM', 'http://stream.nightride.fm/ebsm.mp3', 'Electronic', 1),
(24, 'Nightride Horrorsynth', 'http://stream.nightride.fm/horrorsynth.mp3', 'Synthwave', 1),
(25, 'SomaFM Groove Salad', 'http://ice5.somafm.com/groovesalad-128-mp3', 'Chill', 1),
(26, 'SomaFM Groove Salad Classic', 'http://ice5.somafm.com/gsclassic-128-mp3', 'Chill', 1),
(27, 'SomaFM Drone Zone', 'http://ice5.somafm.com/dronezone-128-mp3', 'Ambient', 1),
(28, 'SomaFM Secret Agent', 'http://ice5.somafm.com/secretagent-128-mp3', 'Lounge', 1),
(29, 'SomaFM Space Station Soma', 'http://ice5.somafm.com/spacestation-128-mp3', 'Ambient', 1),
(30, 'SomaFM Beat Blender', 'http://ice5.somafm.com/beatblender-128-mp3', 'Electronic', 1),
(31, 'SomaFM DEF CON Radio', 'http://ice5.somafm.com/defcon-128-mp3', 'Electronic', 1),
(32, 'SomaFM Lush', 'http://ice5.somafm.com/lush-128-mp3', 'Chill', 1),
(33, 'SomaFM Indie Pop Rocks', 'http://ice5.somafm.com/indiepop-128-mp3', 'Indie', 1),
(34, 'SomaFM PopTron', 'http://ice5.somafm.com/poptron-128-mp3', 'Pop', 1),
(35, 'SomaFM Cliqhop', 'http://ice5.somafm.com/cliqhop-128-mp3', 'Electronic', 1),
(36, 'SomaFM Digitalis', 'http://ice5.somafm.com/digitalis-128-mp3', 'Electronic', 1),
(37, 'SomaFM Dub Step Beyond', 'http://ice5.somafm.com/dubstep-128-mp3', 'Electronic', 1),
(38, 'SomaFM Illinois Street Lounge', 'http://ice5.somafm.com/illstreet-128-mp3', 'Lounge', 1),
(39, 'SomaFM Mission Control', 'http://ice5.somafm.com/missioncontrol-128-mp3', 'Ambient', 1),
(40, 'SomaFM Deep Space One', 'http://ice5.somafm.com/deepspaceone-128-mp3', 'Ambient', 1),
(41, 'SomaFM Sonic Universe', 'http://ice5.somafm.com/sonicuniverse-128-mp3', 'Jazz', 1),
(42, 'SomaFM Fluid', 'http://ice5.somafm.com/fluid-128-mp3', 'Hip Hop', 1),
(43, 'SomaFM Doomed', 'http://ice5.somafm.com/doomed-128-mp3', 'Dark', 1),
(44, 'SomaFM Black Rock FM', 'http://ice5.somafm.com/brfm-128-mp3', 'Eclectic', 1),
(45, 'SomaFM Covers', 'http://ice5.somafm.com/covers-128-mp3', 'Eclectic', 1),
(46, 'SomaFM Left Coast 70s', 'http://ice5.somafm.com/seventies-128-mp3', 'Classic', 1),
(47, 'SomaFM Folk Forward', 'http://ice5.somafm.com/folkfwd-128-mp3', 'Folk', 1),
(48, 'SomaFM Boot Liquor', 'http://ice5.somafm.com/bootliquor-128-mp3', 'Country', 1),
(49, 'SomaFM Metal Detector', 'http://ice5.somafm.com/metal-128-mp3', 'Metal', 1),
(50, 'SomaFM Heavyweight Reggae', 'http://ice5.somafm.com/reggae-128-mp3', 'Reggae', 1),
(51, 'SomaFM Suburbs of Goa', 'http://ice5.somafm.com/suburbsofgoa-128-mp3', 'World', 1),
(52, 'SomaFM Xmas in Frisko', 'http://ice5.somafm.com/xmasinfrisko-128-mp3', 'Seasonal', 1),
(53, 'SomaFM Christmas Lounge', 'http://ice5.somafm.com/christmas-128-mp3', 'Seasonal', 1),
(54, 'SomaFM Jolly Ol Soul', 'http://ice5.somafm.com/jollysoul-128-mp3', 'Seasonal', 1),
(55, 'KEXP 90.3 Seattle', 'http://live-mp3-128.kexp.org/kexp128.mp3', 'Alternative', 1),
(56, 'KEXP 48k AAC', 'http://live-aacplus-64.kexp.org/kexp64.aac', 'Alternative', 1),
(57, 'WFMU Main', 'http://stream0.wfmu.org/freeform-128k', 'Eclectic', 1),
(58, 'WFMU Rock n Soul', 'http://stream0.wfmu.org/rocknsoul-128k', 'Rock', 1),
(59, 'KCRW Eclectic24', 'http://kcrw.streamguys1.com/kcrw_192k_mp3_e24', 'Eclectic', 1),
(60, 'KCRW Live', 'http://kcrw.streamguys1.com/kcrw_192k_mp3_on_air', 'Eclectic', 1),
(61, 'Radio Swiss Jazz', 'http://stream.srg-ssr.ch/m/rsj/mp3_128', 'Jazz', 1),
(62, 'Radio Swiss Pop', 'http://stream.srg-ssr.ch/m/rsp/mp3_128', 'Pop', 1),
(63, 'Radio Swiss Classic', 'http://stream.srg-ssr.ch/m/rsc_de/mp3_128', 'Classic', 1),
(64, 'Venice Classic Radio', 'http://uk2.streamingpulse.com:8000/veniceclassic', 'Classic', 1),
(65, 'Jazz Radio France', 'http://jazzradio.ice.infomaniak.ch/jazzradio-high.mp3', 'Jazz', 1),
(66, 'Jazz Radio Lounge', 'http://jazzlounge.ice.infomaniak.ch/jazzlounge-high.mp3', 'Lounge', 1),
(67, 'Jazz Radio Blues', 'http://jazzblues.ice.infomaniak.ch/jazzblues-high.mp3', 'Blues', 1),
(68, 'Radio Nova', 'http://novazz.ice.infomaniak.ch/novazz-128.mp3', 'Eclectic', 1),
(69, 'Pinguin Radio', 'http://streams.pinguinradio.com/PinguinRadio192.mp3', 'Alternative', 1),
(70, 'Pinguin Classics', 'http://streams.pinguinradio.com/PinguinClassics192.mp3', 'Classic Rock', 1),
(71, 'Pinguin On The Rocks', 'http://streams.pinguinradio.com/PinguinOnTheRocks192.mp3', 'Rock', 1),
(72, 'Classic FM UK', 'http://media-ice.musicradio.com/ClassicFMMP3', 'Classic', 1),
(73, 'Capital UK', 'http://media-ice.musicradio.com/CapitalMP3', 'Pop', 1),
(74, 'Heart UK', 'http://media-ice.musicradio.com/HeartUKMP3', 'Pop', 1),
(75, 'LBC UK', 'http://media-ice.musicradio.com/LBCUKMP3', 'Talk', 1),
(76, 'Smooth UK', 'http://media-ice.musicradio.com/SmoothUKMP3', 'Easy', 1),
(77, 'Gold UK', 'http://media-ice.musicradio.com/GoldMP3', 'Classic', 1),
(78, 'Absolute Radio', 'http://edge-bauerall-01-gos2.sharp-stream.com/absolute.mp3', 'Rock', 1),
(79, 'Kiss UK', 'http://edge-bauerall-01-gos2.sharp-stream.com/kissnational.mp3', 'Pop', 1),
(80, 'Magic UK', 'http://edge-bauerall-01-gos2.sharp-stream.com/magicnational.mp3', 'Easy', 1),
(81, 'Planet Rock', 'http://edge-bauerall-01-gos2.sharp-stream.com/planetrock.mp3', 'Rock', 1),
(82, 'Heat Radio', 'http://edge-bauerall-01-gos2.sharp-stream.com/heat.mp3', 'Pop', 1),
(83, 'Egypt On Air', 'https://radio.socialgenix.com/8004/stream', 'Egyptian', 1),
(84, 'Cairo 99.9 FM', 'https://stream.zeno.fm/zm4deqv60xhvv', 'Egyptian', 1),
(85, 'Arabic Mix FM', 'https://stream-283.zeno.fm/efx5psd00qruv', 'Egyptian', 1),
(86, 'Arabic Mix Drama', 'https://stream-288.zeno.fm/ct8habf171zuv', 'Egyptian', 1),
(87, 'Arab DJ', 'https://stream-283.zeno.fm/na3vpvn10qruv', 'Egyptian', 1),
(88, 'Alwan FM', 'https://stream-176.zeno.fm/fhhhcrvxhchvv', 'Egyptian', 1),
(89, 'Radio ALAyaam FM', 'https://stream-178.zeno.fm/x2u58hd0gchvv', 'Egyptian', 1),
(90, '99 FM', 'http://radio.hvips.com:8007/', 'Egyptian', 1),
(91, 'Radio 90s FM', 'https://stream-288.zeno.fm/0dh9whxvcfhvv', 'Egyptian', 1),
(92, 'Radio 514', 'http://n06.radiojar.com/ps7z45v12k8uv', 'Egyptian', 1);
